name: data factory with dns failover
on:
  workflow_call:
    inputs:
      private_dns_zone_subscription_Id:
        required: true
        type: string
      private_dns_zone_resource_group_name:
        required: true
        type: string
      data_factory_private_dns_zone_record_name:
        required: true
        type: string
      data_factory_private_dns_zone_name:
        required: true
        type: string
      data_factory_primary_private_endpoint_IP:
        required: true
        type: string
      data_factory_secondary_private_endpoint_IP:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS_DELOITTE_SUB:
        required: true  
jobs:  
  data_factory_dns_failover:
    permissions:
      contents: none
    runs-on: ubuntu-latest       
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        repository: SNawazmac/data_factory_dns_failover
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_DELOITTE_SUB}}
        enable-AzPSSession: true   
    - name: Update recordset of Private DNS Zone
      uses: azure/powershell@v1
      with:
        inlineScript: |
         ./data_factory_dns_failover.ps1 -private_dns_zone_subscription_Id "${{inputs.private_dns_zone_subscription_Id}}" -private_dns_zone_resource_group_name "${{inputs.private_dns_zone_resource_group_name}}" -data_factory_private_dns_zone_name "${{inputs.data_factory_private_dns_zone_name}}" -data_factory_private_dns_zone_record_name "${{inputs.data_factory_private_dns_zone_record_name}}" -data_factory_primary_private_endpoint_IP "${{inputs.data_factory_primary_private_endpoint_IP}}" -data_factory_secondary_private_endpoint_IP "${{inputs.data_factory_secondary_private_endpoint_IP}}"
        azPSVersion: "latest"
