name: data factory link pe to dns
on:
  workflow_call:
    inputs:
      private_dns_zone_subscription_Id:
        required: true
        type: string
      private_dns_zone_resource_group_name:
        required: true
        type: string
      data_factory_private_dns_zone_group_name:
        required: true
        type: string
      data_factory_private_dns_zone_name:
        required: true
        type: string
      secondary_private_endpoint_resource_group_name:
        required: true
        type: string
      secondary_private_endpoint_subscription_Id:
        required: true
        type: string
      secondary_private_endpoint_name:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS_DELOITTE_SUB:
        required: true  
jobs:  
  link_pe_to_dns:
    permissions:
      contents: none
    runs-on: ubuntu-latest       
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        repository: SNawazmac/data_factory_dns_failover
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DELOITTE_SUB }}
        enable-AzPSSession: true   
    - name: Link PE to Private DNS
      uses: azure/powershell@v1
      with:
        inlineScript: |
         ./data_factory_link_pe_to_dns.ps1 -private_dns_zone_subscription_Id "${{ inputs.private_dns_zone_subscription_Id }}" -private_dns_zone_resource_group_name "${{ inputs.private_dns_zone_resource_group_name }}" -data_factory_private_dns_zone_group_name "${{ inputs.data_factory_private_dns_zone_group_name }}" -data_factory_private_dns_zone_name "${{ inputs.data_factory_private_dns_zone_name }}" -secondary_private_endpoint_resource_group_name "${{ inputs.secondary_private_endpoint_resource_group_name }}" -secondary_private_endpoint_subscription_Id "${{ inputs.secondary_private_endpoint_subscription_Id }}" -secondary_private_endpoint_name "${{ inputs.secondary_private_endpoint_name }}" 
        azPSVersion: "latest"
